language: node_js
node_js:
- '9'
- '10'
- '11'
- '12'

script:
  - npm t
  - npm run build

jobs:
  include:
    - stage: Coverage Report
    - node_js node
    - script: jest --silent && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage

deploy:
  provider: npm
  email: djtthompson@gmail.com
  api_key:
    secure: AECeZvLU7xTuNl0KBFYuSWbJfKo6XyXhs2oszEqw7v36qVL8zJLz+DOPkRKOvC2WL23t77MuTUvApTLDLqGhKqYyoQCQ4w4N7mgMoQnnYA0lvxUylbuFWAikZro3u5E0v7/ljVGLy4ZIvSi94d351+nu9SH10WcghdyOrOhulEOmEvCAo94EYnKJAafSdyZRLXYTwJHj6SnY3G4RhAse9cjWjGPqqWj75m9SXVwJlD/UGhSAWk6JCfB2l7GFBNjjDT3b/aLfzzQgAZhBlUvIfa42av47L8jouFmAcvMc8twmqftdPb+KxzYSO9oBHZXijjQtoOUd+rctDQ8DZGGI2ub8B//9OZIkuMjwMGNffKwKsphnWDNn5NStRS4P/zGnp9IMNCnkp5RQ9+s+QPxlA8j2G0ZS0OsZOslLXAD0cwQbm2iNyCiQFm8s+KFuM0MeaEB1aJgrP87whry0cL+cIafi8FWD+2AarqalGmj/9ctZHdifOXD6N1kdAwOHcDm7oy3cMrdwx4RJHiTA6r5M1H8Zx9Utf6yk/g0hnGyZWD4/fxWBCAZvTRNSE6viFs4J17SZZZ7h0b6Ct0tWahniJWauneZ10LhMcFStz05t9n4Zq4tiT0V8wAXzPj6Yx8rtejIa7eCCnCXhgk9Ti4jYqP5/Y1Vptw1SQJwIonsi4as=
  on:
    tags: true
    branch: master
