[build]
    base = "docs/"
    publish = "build/"
    command = "yarn build"

[[headers]]
    for = "/*"

    [headers.values]
        X-Frame-Options = "DENY"
        X-XSS-Protection = "1; mode=block"
        cache-control = '''
        max-age=0,
        no-cache,
        must-revalidate'''
